name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  msvc:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v3
    - name: Install da
      run: git clone --depth=1 https://github.com/dragon-archer/da.git
    - name: Install spdlog
      run: vcpkg update && vcpkg install spdlog:x64-windows
    - name: Run CMake
      run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -Ddascript_BuildTests=ON -DWITH_DA_SUBMODULE=True
    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}
    - name: Test
      run: cd build && ctest -C ${{ matrix.build_type }} --output-on-failure
